.TH ACFCONV "1" "2023\-11\-21" "acfconv"
.SH NAME
acfconv
.SH SYNOPSIS
.B acfconv
[-h] [-o OUTPUT] [-s SIZE] filename
.SH DESCRIPTION
generate .acf font files from .ttf or .otf files

.TP
\fBfilename\fR
input filename

.SH OPTIONS
.TP
\fB\-o\fR \fI\,OUTPUT\/\fR, \fB\-\-output\fR \fI\,OUTPUT\/\fR
output filename

.TP
\fB\-s\fR \fI\,SIZE\/\fR, \fB\-\-size\fR \fI\,SIZE\/\fR
font size in pixels (default = 16)
